# Generated by Django 3.1.3 on 2021-05-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taste_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='project',
        ),
        migrations.AlterField(
            model_name='taste',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'RUNNING'), (0, 'STOP'), (3, 'RESUME'), (2, 'PAUSE')], default=0, verbose_name='任务状态'),
        ),
    ]
