# Generated by Django 3.1.3 on 2021-05-13 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210513_0935'),
        ('taste_user', '0002_auto_20210513_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='项目名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taste',
            name='status',
            field=models.SmallIntegerField(choices=[(3, 'RESUME'), (1, 'RUNNING'), (0, 'STOP'), (2, 'PAUSE')], default=0, verbose_name='任务状态'),
        ),
    ]
