# Generated by Django 3.1.3 on 2021-05-13 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('env', '0001_initial'),
        ('apitest', '0001_initial'),
        ('taste_user', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taste_user.taste', verbose_name='报告对应的任务'),
        ),
        migrations.AddField(
            model_name='plan',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.environment', verbose_name='环境'),
        ),
        migrations.AddField(
            model_name='plan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='interface',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='case',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='项目'),
        ),
    ]
