# Generated by Django 3.1.3 on 2021-05-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '失效'), (1, '有效')], default=1, verbose_name='环境状态'),
        ),
    ]
